### ISSUE TITLE
redux conflict

### ISSUE THREAD

**Issue by yanbober** [jamestierney/redux-lang#7]
how to handle the redux connect function and reduxLang function use in one component？
such as your App.js：
......
export default reduxLang('home')(App)

then，the redux connect how to use？
**export default connect()(App);** will conflict with **export default reduxLang('home')(App);**。

**Comment by adamTrz** [comment]
Little late, but nevertheless: ;)

export default reduxLang('home')(connect()(App))

**Comment by jamestierney** [comment]
Sorry this is so late, but the answer given by adamTrz is what I do to achieve this!
